---
# tasks file for server-setup
- name: copy old ssh port
  set_fact:
    old_ssh_port: '{{ansible_ssh_port}}'
  when: 'ansible_ssh_port not in ssh_server_ports'
  tags: ['server-setup']

- name: Reset ssh port
  set_fact:
    ansible_ssh_port={{ssh_server_ports[0]}}
    ask_pass=False
  when: 'ansible_ssh_port not in ssh_server_ports'
  tags: ['server-setup']
