---
# tasks file for server-setup
- name: copy old ssh port
  set_fact:
    old_ssh_port: '{{ansible_port}}'
  when: default_ssh_configured is defined
  tags: ['server-setup']

- name: Reset ssh port
  set_fact:
    ansible_port={{configured_port}}
    ansible_user={{configured_user}}
    ask_pass=False
  when: default_ssh_configured is defined
  tags: ['server-setup']

- name: Flush Handlers
  meta: flush_handlers

