---
galaxy_info:
  author: Ritesh Kadmawala
  description: Set of roles to do server hardening
  company: Loanzen Technologies Private Ltd

  license: MIT

  min_ansible_version: 1.2

dependencies:
    - { role: apt }
    - { role: sysctl }
    - { role: users }
    - { role: paths }
    - { role: alias }
    - { role: dev-sec.ssh-hardening, tags: ['ssh-hardening'] }
    - { role: ansible-fail2ban, tags: ['fail2ban']}
    - { role: ufw }
    - { role: tersmitten.hostname, tags: ['hostname'] }

